/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yyms.adp.aaa.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.yyms.adp.aaa.model.YCustomer;
import com.yyms.adp.aaa.model.YCustomerModel;
import com.yyms.adp.aaa.model.YCustomerSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the YCustomer service. Represents a row in the &quot;CS_YCustomer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.yyms.adp.aaa.model.YCustomerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link YCustomerImpl}.
 * </p>
 *
 * @author USER
 * @see YCustomerImpl
 * @see com.yyms.adp.aaa.model.YCustomer
 * @see com.yyms.adp.aaa.model.YCustomerModel
 * @generated
 */
@JSON(strict = true)
public class YCustomerModelImpl extends BaseModelImpl<YCustomer>
	implements YCustomerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a y customer model instance should use the {@link com.yyms.adp.aaa.model.YCustomer} interface instead.
	 */
	public static final String TABLE_NAME = "CS_YCustomer";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "yCustomerId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "customerName", Types.VARCHAR },
			{ "customerEmail", Types.VARCHAR },
			{ "customerAddress", Types.VARCHAR },
			{ "customerNRC", Types.VARCHAR },
			{ "customerContact", Types.VARCHAR },
			{ "payment", Types.VARCHAR },
			{ "yServicesId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table CS_YCustomer (uuid_ VARCHAR(75) null,yCustomerId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,customerName VARCHAR(75) null,customerEmail VARCHAR(75) null,customerAddress VARCHAR(75) null,customerNRC VARCHAR(75) null,customerContact VARCHAR(75) null,payment VARCHAR(75) null,yServicesId LONG)";
	public static final String TABLE_SQL_DROP = "drop table CS_YCustomer";
	public static final String ORDER_BY_JPQL = " ORDER BY yCustomer.customerName DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CS_YCustomer.customerName DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.yyms.adp.aaa.model.YCustomer"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.yyms.adp.aaa.model.YCustomer"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.yyms.adp.aaa.model.YCustomer"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;
	public static long CUSTOMERNAME_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static YCustomer toModel(YCustomerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		YCustomer model = new YCustomerImpl();

		model.setUuid(soapModel.getUuid());
		model.setYCustomerId(soapModel.getYCustomerId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCustomerName(soapModel.getCustomerName());
		model.setCustomerEmail(soapModel.getCustomerEmail());
		model.setCustomerAddress(soapModel.getCustomerAddress());
		model.setCustomerNRC(soapModel.getCustomerNRC());
		model.setCustomerContact(soapModel.getCustomerContact());
		model.setPayment(soapModel.getPayment());
		model.setYServicesId(soapModel.getYServicesId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<YCustomer> toModels(YCustomerSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<YCustomer> models = new ArrayList<YCustomer>(soapModels.length);

		for (YCustomerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.yyms.adp.aaa.model.YCustomer"));

	public YCustomerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _yCustomerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setYCustomerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _yCustomerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return YCustomer.class;
	}

	@Override
	public String getModelClassName() {
		return YCustomer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("yCustomerId", getYCustomerId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("customerName", getCustomerName());
		attributes.put("customerEmail", getCustomerEmail());
		attributes.put("customerAddress", getCustomerAddress());
		attributes.put("customerNRC", getCustomerNRC());
		attributes.put("customerContact", getCustomerContact());
		attributes.put("payment", getPayment());
		attributes.put("yServicesId", getYServicesId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long yCustomerId = (Long)attributes.get("yCustomerId");

		if (yCustomerId != null) {
			setYCustomerId(yCustomerId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String customerName = (String)attributes.get("customerName");

		if (customerName != null) {
			setCustomerName(customerName);
		}

		String customerEmail = (String)attributes.get("customerEmail");

		if (customerEmail != null) {
			setCustomerEmail(customerEmail);
		}

		String customerAddress = (String)attributes.get("customerAddress");

		if (customerAddress != null) {
			setCustomerAddress(customerAddress);
		}

		String customerNRC = (String)attributes.get("customerNRC");

		if (customerNRC != null) {
			setCustomerNRC(customerNRC);
		}

		String customerContact = (String)attributes.get("customerContact");

		if (customerContact != null) {
			setCustomerContact(customerContact);
		}

		String payment = (String)attributes.get("payment");

		if (payment != null) {
			setPayment(payment);
		}

		Long yServicesId = (Long)attributes.get("yServicesId");

		if (yServicesId != null) {
			setYServicesId(yServicesId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getYCustomerId() {
		return _yCustomerId;
	}

	@Override
	public void setYCustomerId(long yCustomerId) {
		_yCustomerId = yCustomerId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCustomerName() {
		if (_customerName == null) {
			return StringPool.BLANK;
		}
		else {
			return _customerName;
		}
	}

	@Override
	public void setCustomerName(String customerName) {
		_columnBitmask = -1L;

		_customerName = customerName;
	}

	@JSON
	@Override
	public String getCustomerEmail() {
		if (_customerEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _customerEmail;
		}
	}

	@Override
	public void setCustomerEmail(String customerEmail) {
		_customerEmail = customerEmail;
	}

	@JSON
	@Override
	public String getCustomerAddress() {
		if (_customerAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _customerAddress;
		}
	}

	@Override
	public void setCustomerAddress(String customerAddress) {
		_customerAddress = customerAddress;
	}

	@JSON
	@Override
	public String getCustomerNRC() {
		if (_customerNRC == null) {
			return StringPool.BLANK;
		}
		else {
			return _customerNRC;
		}
	}

	@Override
	public void setCustomerNRC(String customerNRC) {
		_customerNRC = customerNRC;
	}

	@JSON
	@Override
	public String getCustomerContact() {
		if (_customerContact == null) {
			return StringPool.BLANK;
		}
		else {
			return _customerContact;
		}
	}

	@Override
	public void setCustomerContact(String customerContact) {
		_customerContact = customerContact;
	}

	@JSON
	@Override
	public String getPayment() {
		if (_payment == null) {
			return StringPool.BLANK;
		}
		else {
			return _payment;
		}
	}

	@Override
	public void setPayment(String payment) {
		_payment = payment;
	}

	@JSON
	@Override
	public long getYServicesId() {
		return _yServicesId;
	}

	@Override
	public void setYServicesId(long yServicesId) {
		_yServicesId = yServicesId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				YCustomer.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			YCustomer.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public YCustomer toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (YCustomer)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		YCustomerImpl yCustomerImpl = new YCustomerImpl();

		yCustomerImpl.setUuid(getUuid());
		yCustomerImpl.setYCustomerId(getYCustomerId());
		yCustomerImpl.setGroupId(getGroupId());
		yCustomerImpl.setCompanyId(getCompanyId());
		yCustomerImpl.setUserId(getUserId());
		yCustomerImpl.setUserName(getUserName());
		yCustomerImpl.setCreateDate(getCreateDate());
		yCustomerImpl.setModifiedDate(getModifiedDate());
		yCustomerImpl.setCustomerName(getCustomerName());
		yCustomerImpl.setCustomerEmail(getCustomerEmail());
		yCustomerImpl.setCustomerAddress(getCustomerAddress());
		yCustomerImpl.setCustomerNRC(getCustomerNRC());
		yCustomerImpl.setCustomerContact(getCustomerContact());
		yCustomerImpl.setPayment(getPayment());
		yCustomerImpl.setYServicesId(getYServicesId());

		yCustomerImpl.resetOriginalValues();

		return yCustomerImpl;
	}

	@Override
	public int compareTo(YCustomer yCustomer) {
		int value = 0;

		value = getCustomerName().compareTo(yCustomer.getCustomerName());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof YCustomer)) {
			return false;
		}

		YCustomer yCustomer = (YCustomer)obj;

		long primaryKey = yCustomer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		YCustomerModelImpl yCustomerModelImpl = this;

		yCustomerModelImpl._originalUuid = yCustomerModelImpl._uuid;

		yCustomerModelImpl._originalGroupId = yCustomerModelImpl._groupId;

		yCustomerModelImpl._setOriginalGroupId = false;

		yCustomerModelImpl._originalCompanyId = yCustomerModelImpl._companyId;

		yCustomerModelImpl._setOriginalCompanyId = false;

		yCustomerModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<YCustomer> toCacheModel() {
		YCustomerCacheModel yCustomerCacheModel = new YCustomerCacheModel();

		yCustomerCacheModel.uuid = getUuid();

		String uuid = yCustomerCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			yCustomerCacheModel.uuid = null;
		}

		yCustomerCacheModel.yCustomerId = getYCustomerId();

		yCustomerCacheModel.groupId = getGroupId();

		yCustomerCacheModel.companyId = getCompanyId();

		yCustomerCacheModel.userId = getUserId();

		yCustomerCacheModel.userName = getUserName();

		String userName = yCustomerCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			yCustomerCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			yCustomerCacheModel.createDate = createDate.getTime();
		}
		else {
			yCustomerCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			yCustomerCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			yCustomerCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		yCustomerCacheModel.customerName = getCustomerName();

		String customerName = yCustomerCacheModel.customerName;

		if ((customerName != null) && (customerName.length() == 0)) {
			yCustomerCacheModel.customerName = null;
		}

		yCustomerCacheModel.customerEmail = getCustomerEmail();

		String customerEmail = yCustomerCacheModel.customerEmail;

		if ((customerEmail != null) && (customerEmail.length() == 0)) {
			yCustomerCacheModel.customerEmail = null;
		}

		yCustomerCacheModel.customerAddress = getCustomerAddress();

		String customerAddress = yCustomerCacheModel.customerAddress;

		if ((customerAddress != null) && (customerAddress.length() == 0)) {
			yCustomerCacheModel.customerAddress = null;
		}

		yCustomerCacheModel.customerNRC = getCustomerNRC();

		String customerNRC = yCustomerCacheModel.customerNRC;

		if ((customerNRC != null) && (customerNRC.length() == 0)) {
			yCustomerCacheModel.customerNRC = null;
		}

		yCustomerCacheModel.customerContact = getCustomerContact();

		String customerContact = yCustomerCacheModel.customerContact;

		if ((customerContact != null) && (customerContact.length() == 0)) {
			yCustomerCacheModel.customerContact = null;
		}

		yCustomerCacheModel.payment = getPayment();

		String payment = yCustomerCacheModel.payment;

		if ((payment != null) && (payment.length() == 0)) {
			yCustomerCacheModel.payment = null;
		}

		yCustomerCacheModel.yServicesId = getYServicesId();

		return yCustomerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", yCustomerId=");
		sb.append(getYCustomerId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", customerName=");
		sb.append(getCustomerName());
		sb.append(", customerEmail=");
		sb.append(getCustomerEmail());
		sb.append(", customerAddress=");
		sb.append(getCustomerAddress());
		sb.append(", customerNRC=");
		sb.append(getCustomerNRC());
		sb.append(", customerContact=");
		sb.append(getCustomerContact());
		sb.append(", payment=");
		sb.append(getPayment());
		sb.append(", yServicesId=");
		sb.append(getYServicesId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.yyms.adp.aaa.model.YCustomer");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yCustomerId</column-name><column-value><![CDATA[");
		sb.append(getYCustomerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerName</column-name><column-value><![CDATA[");
		sb.append(getCustomerName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerEmail</column-name><column-value><![CDATA[");
		sb.append(getCustomerEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerAddress</column-name><column-value><![CDATA[");
		sb.append(getCustomerAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerNRC</column-name><column-value><![CDATA[");
		sb.append(getCustomerNRC());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerContact</column-name><column-value><![CDATA[");
		sb.append(getCustomerContact());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>payment</column-name><column-value><![CDATA[");
		sb.append(getPayment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>yServicesId</column-name><column-value><![CDATA[");
		sb.append(getYServicesId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = YCustomer.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			YCustomer.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _yCustomerId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _customerName;
	private String _customerEmail;
	private String _customerAddress;
	private String _customerNRC;
	private String _customerContact;
	private String _payment;
	private long _yServicesId;
	private long _columnBitmask;
	private YCustomer _escapedModel;
}