/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yyms.adp.aaa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the YService service. Represents a row in the &quot;CS_YService&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.yyms.adp.aaa.model.impl.YServiceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.yyms.adp.aaa.model.impl.YServiceImpl}.
 * </p>
 *
 * @author USER
 * @see YService
 * @see com.yyms.adp.aaa.model.impl.YServiceImpl
 * @see com.yyms.adp.aaa.model.impl.YServiceModelImpl
 * @generated
 */
public interface YServiceModel extends BaseModel<YService>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a y service model instance should use the {@link YService} interface instead.
	 */

	/**
	 * Returns the primary key of this y service.
	 *
	 * @return the primary key of this y service
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this y service.
	 *
	 * @param primaryKey the primary key of this y service
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this y service.
	 *
	 * @return the uuid of this y service
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this y service.
	 *
	 * @param uuid the uuid of this y service
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the y service ID of this y service.
	 *
	 * @return the y service ID of this y service
	 */
	public long getYServiceId();

	/**
	 * Sets the y service ID of this y service.
	 *
	 * @param yServiceId the y service ID of this y service
	 */
	public void setYServiceId(long yServiceId);

	/**
	 * Returns the group ID of this y service.
	 *
	 * @return the group ID of this y service
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this y service.
	 *
	 * @param groupId the group ID of this y service
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this y service.
	 *
	 * @return the company ID of this y service
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this y service.
	 *
	 * @param companyId the company ID of this y service
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this y service.
	 *
	 * @return the user ID of this y service
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this y service.
	 *
	 * @param userId the user ID of this y service
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this y service.
	 *
	 * @return the user uuid of this y service
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this y service.
	 *
	 * @param userUuid the user uuid of this y service
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this y service.
	 *
	 * @return the user name of this y service
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this y service.
	 *
	 * @param userName the user name of this y service
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this y service.
	 *
	 * @return the create date of this y service
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this y service.
	 *
	 * @param createDate the create date of this y service
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this y service.
	 *
	 * @return the modified date of this y service
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this y service.
	 *
	 * @param modifiedDate the modified date of this y service
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the service name of this y service.
	 *
	 * @return the service name of this y service
	 */
	@AutoEscape
	public String getServiceName();

	/**
	 * Sets the service name of this y service.
	 *
	 * @param serviceName the service name of this y service
	 */
	public void setServiceName(String serviceName);

	/**
	 * Returns the service price of this y service.
	 *
	 * @return the service price of this y service
	 */
	@AutoEscape
	public String getServicePrice();

	/**
	 * Sets the service price of this y service.
	 *
	 * @param servicePrice the service price of this y service
	 */
	public void setServicePrice(String servicePrice);

	/**
	 * Returns the service des of this y service.
	 *
	 * @return the service des of this y service
	 */
	@AutoEscape
	public String getServiceDes();

	/**
	 * Sets the service des of this y service.
	 *
	 * @param serviceDes the service des of this y service
	 */
	public void setServiceDes(String serviceDes);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.yyms.adp.aaa.model.YService yService);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.yyms.adp.aaa.model.YService> toCacheModel();

	@Override
	public com.yyms.adp.aaa.model.YService toEscapedModel();

	@Override
	public com.yyms.adp.aaa.model.YService toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}